name: Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            arch: Apple-Silicon
          - target: x86_64-apple-darwin
            arch: Intel

    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build -- --target ${{ matrix.target }}

      - name: Rename DMG
        run: |
          cd src-tauri/target/${{ matrix.target }}/release/bundle/dmg
          for file in *.dmg; do
            mv "$file" "IPTV-Player-${GITHUB_REF_NAME}-macOS-${{ matrix.arch }}.dmg"
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPTV-Player-${{ matrix.arch }}
          path: src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
